### ISSUE TITLE
ALBERT Data Prep Script

### ISSUE THREAD

**Issue by zzj0402** [zzj0402/natural-questions-environment#5]
BERT-base prep script:  

BERT-joint prep script:

**Comment by zzj0402** [comment]
The BERT-joint and BERT-base models share same format of vocabulary.
bert-base:  
![屏幕快照 2020-01-14 上午11 23 23](https://user-images.githubusercontent.com/15345547/72297326-946ccb00-36c0-11ea-886c-01baa393503c.png)
bert-joint:  
![屏幕快照 2020-01-14 上午11 23 51](https://user-images.githubusercontent.com/15345547/72297327-95056180-36c0-11ea-83b3-1e79b555a756.png)

**Comment by zzj0402** [comment]
But cannot share the same script.

**Comment by zzj0402** [comment]
```bash
Processing example #: 0
:Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/root/language/language/question_answering/bert_joint/prepare_nq_data.py", line 92, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/root/language/language/question_answering/bert_joint/prepare_nq_data.py", line 72, in main
    for instance in creator_fn.process(example):
  File "language/question_answering/bert_joint/run_nq.py", line 751, in process
    convert_single_example(nq_example, self.tokenizer, self.is_training))
  File "language/question_answering/bert_joint/run_nq.py", line 637, in convert_single_example
    input_ids = tokenizer.convert_tokens_to_ids(tokens)
  File "bert/tokenization.py", line 179, in convert_tokens_to_ids
    return convert_by_vocab(self.vocab, tokens)
  File "bert/tokenization.py", line 140, in convert_by_vocab
    output.append(vocab[item])
KeyError: '[Q]'
```
